name: Fetch Tweets

on:
  schedule:
    - cron: "30 10 * * 1-5"  # For example, 10:30 UTC Monday-Friday
  workflow_dispatch: # So you can run it manually from the Actions tab if you want

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch_tweets.py
      run: python fetch_tweets.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add tweets.txt
        git commit -m "Update tweets.txt"
        git push
