name: Fetch Tweets

on:
  schedule:
    - cron: "30 10 * * 1-5"  # Runs Mon-Fri at 10:30 UTC (adjust times as needed)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tweet fetcher
        run: python fetch_tweets.py

      - name: Commit tweets.txt
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add tweets.txt
          git commit -m "Update tweets feed" || echo "No changes to commit"
          git push
