name: Fetch Tweets (Nitter RSS)

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes; adjust if you like
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      NITTER_BASE: 'https://nitter.poast.org'
      DAYS: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run multi-account tweet fetcher
        run: python fetch_multi.py

      - name: Commit results if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A tweets.txt tweets.xlsx || true
          if ! git diff --cached --quiet; then
            git commit -m "Update tweets via Nitter RSS"
            git push
          else
            echo "No changes to commit."
          fi
