name: Fetch Tweets via Selenium

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours; adjust as needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-tweets:
    runs-on: ubuntu-latest
    env:
      gmail: ${{ secrets.gmail }}
      Gmail_Password: ${{ secrets.Gmail_Password }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install selenium pandas openpyxl

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          # Ensure chromedriver is in PATH; adjust the path if necessary:
          sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run Tweet Scraper
        run: python fetch_tweets.py
